### ISSUE TITLE
为什么我发布后总是拉取不到权限,用JB运行就能拉取到

### ISSUE THREAD

**Issue by GitXieJun** [colinin/abp-vue-admin-element-typescript#108]
![E2221813-CE8A-4722-BCBE-3D0399F5BF12](https://user-images.githubusercontent.com/45811979/96226671-948a5600-0fc5-11eb-9153-00dc666f7b77.png)

**Comment by colinin** [comment]
清除下浏览器缓存呢，我这几天忙得没看到

**Comment by GitXieJun** [comment]
咨询下是在哪里初始化权限写入redis缓存，十分感谢

**Comment by colinin** [comment]
> 咨询下是在哪里初始化权限写入redis缓存，十分感谢

Volo.Abp.PermissionManagement模块里面，PermissionStore引入了分布式缓存

**Comment by colinin** [comment]
> 咨询下是在哪里初始化权限写入redis缓存，十分感谢

因为官方的Volo.Abp.PermissionManagement.PermissionAppService是直接通过数据库查询权限，有很大的性能损耗，所以我自己重写了PermissionAppService通过PermissionStore来查询，优先查询缓存

**Comment by GitXieJun** [comment]
好的谢谢

**Comment by colinin** [comment]
> > 咨询下是在哪里初始化权限写入redis缓存，十分感谢
> 
> 因为官方的Volo.Abp.PermissionManagement.PermissionAppService是直接通过数据库查询权限，有很大的性能损耗，所以我自己重写了PermissionAppService通过PermissionStore来查询，优先查询缓存

应该说是重写了PermissionManager

**Comment by GitXieJun** [comment]
因为发布后总是获取不到权限所以想找下哪里初始化权限，感谢

**Comment by colinin** [comment]
> 初始化

都在PermissionStore中，最好把多个项目的Redis配置项统一一下，不然的话多个缓存空间不同步，就会出现各模块获取的缓存不一致的问题

**Comment by colinin** [comment]
前端如果出现权限没有了，可以尝试多刷新两下页面，刷新页面会用token重新请求application-configuration这个api的，如果还是不行就清理浏览器缓存

**Comment by GitXieJun** [comment]
好的我研究下

**Comment by colinin** [comment]
太久，关闭
