### ISSUE TITLE
Authorization failed! Given policy has not granted

### ISSUE THREAD

**Issue by GitXieJun** [colinin/abp-vue-admin-element-typescript#136]
我用开发环境运行没有问题，但是发布出来就说Authorization failed! Given policy has not granted

**Comment by GitXieJun** [comment]
![QQ图片20201119193755](https://user-images.githubusercontent.com/45811979/99661487-dc0d7180-2a9e-11eb-8955-bb661988088d.png)
开发环境运行正常，发不出来就是提示授权失败

**Comment by GitXieJun** [comment]
我把redis清空后，然后再登录就一直获取不到权限数据，多次刷新还是这样
![QQ图片20201119234659](https://user-images.githubusercontent.com/45811979/99689122-8bf3d680-2ac1-11eb-9065-e62b6c83575e.png)
可以讲解下为什么吗

**Comment by colinin** [comment]
你的各服务模块配置文件怎么样的,可以发邮件我看看,如果存在服务器连接地址,请用别名替代

比如：

````json
{
  "AuthServer": {
    "Authority": "http://identityServer4/",
    "ApiName": "auth-service"
  }
}

````

**Comment by colinin** [comment]
你这个报错属于网关请求网关管理服务的问题，要确保网关启动项目和网关管理项目的**AuthServer**配置项保持一致

**Comment by colinin** [comment]
> 我把redis清空后，然后再登录就一直获取不到权限数据，多次刷新还是这样
> ![QQ图片20201119234659](https://user-images.githubusercontent.com/45811979/99689122-8bf3d680-2ac1-11eb-9065-e62b6c83575e.png)
> 可以讲解下为什么吗

等我下回把配置文件放出来吧，现在主要是和我正在做的客户项目保持同步，配置文件信息都是真实的服务器

**Comment by GitXieJun** [comment]
这个没有改变过，都是你发的配置文件

**Comment by GitXieJun** [comment]
如果这个我改变过那开发环境也应该不行呢，但是就是发布出来后不行

**Comment by GitXieJun** [comment]
![QQ图片20201120224153](https://user-images.githubusercontent.com/45811979/99812867-ef453d80-2b81-11eb-8a06-db5dbb2bd85f.png)
![QQ图片20201120224220](https://user-images.githubusercontent.com/45811979/99812879-f2402e00-2b81-11eb-953a-d8fb6dcdae05.png)
![QQ图片20201120224246](https://user-images.githubusercontent.com/45811979/99812884-f3715b00-2b81-11eb-99d5-0914b61549c5.png)
![QQ图片20201120224304](https://user-images.githubusercontent.com/45811979/99812889-f4a28800-2b81-11eb-8c1b-f80fe79af180.png)
![QQ图片20201120224334](https://user-images.githubusercontent.com/45811979/99812892-f53b1e80-2b81-11eb-9582-6b5490cfd098.png)
![QQ图片20201120224352](https://user-images.githubusercontent.com/45811979/99812894-f5d3b500-2b81-11eb-88bf-f0ced0577fa8.png)
![QQ图片20201120224412](https://user-images.githubusercontent.com/45811979/99812900-f66c4b80-2b81-11eb-98e5-623ab18a1b71.png)
这个是我的配置文件

**Comment by colinin** [comment]
部署环境是否是容器内部，如果是Docker容器，请公开内部端口，AuthServer服务地址填写IP地址，localhost是开发环境下同一台主机

**Comment by GitXieJun** [comment]
我部署在iis上的，全部放在同一主机的

**Comment by colinin** [comment]
IIS部署的话，如果在同一个网站目录之下，不同应用程序连接端口之后还有一个后缀在，最好部署在不同的网站目录上

**Comment by colinin** [comment]
生产环境下，身份服务器地址填写真实IP地址或者域名，不然外部认证用户连接到服务实例，与服务实例配置的授权服务器地址不匹配，也会出现认证失败

**Comment by GitXieJun** [comment]
如果都是本机就不需要设置ip直接localhost撒

**Comment by colinin** [comment]
那你得应用程序就不支持外部授权了

**Comment by GitXieJun** [comment]
应该是这个问题，我吧vue在在开发环境去调用云服务器部署的api，我等等改下ip试试

**Comment by colinin** [comment]
你这个问题，你先检查下如下几点：

1、ApiGateway.Host启动后，如果获取了Token，会在Redis服务器缓存Token信息，你通过这个Token在jwt.io验证一下，看看Scope和issue是否和ApiGateway.Admin项目匹配，你可以在swagger用这个Token调用一下ApiGateway.Admin的API；

2、如果都匹配的话，你看看platform.abppermissiongrants表中，ProviderName为C，ProviderKey为apigateway-host-client的记录是否存在这几个权限分配信息：ApiGateway.RouteGroup.Export 、ApiGateway.Global.Export、ApiGateway.Route.Export、ApiGateway.DynamicRoute.Export、ApiGateway.DynamicRoute.Export、AggregateRoute，这个也可以通过在redis服务器节点查看

**Comment by GitXieJun** [comment]
好😁

**Comment by GitXieJun** [comment]
![QQ图片20201121141032](https://user-images.githubusercontent.com/45811979/99869171-e006d400-2c03-11eb-9caf-f64842cbdc6b.png)
审计表是在platform这个库里面，我需要配置他的字符串连接对吗

**Comment by GitXieJun** [comment]
但是开发环境又不存在这个问题

**Comment by colinin** [comment]
> ![QQ图片20201121141032](https://user-images.githubusercontent.com/45811979/99869171-e006d400-2c03-11eb-9caf-f64842cbdc6b.png)
> 审计表是在platform这个库里面，我需要配置他的字符串连接对吗

审计日志的连接字符串："AbpAuditLogging": "Server=127.0.0.1;Database=Platform;User Id=root;Password=123456",连接信息改成你的

**Comment by GitXieJun** [comment]
开发环境不报错，是因为开发环境禁用了审计日志的吗

**Comment by colinin** [comment]
Abp的模块的连接有专门的模块名称，通过名称指定的连接信息连接对应的数据库，没有指定配置，默认使用Default节点

**Comment by lazyabp** [comment]
这个问题是因为LINGYUN.ApiGateway.HttpApi.Host项目下的EntityFrameworkCore/HttpApiHostMigrationsDbContextFactory.cs文件中BuildConfiguration方便固定了开发环境配置文件造成的，改一下就可以了
