### ISSUE TITLE
【版本升级】 4.0已经发布

### ISSUE THREAD

**Issue by XuJin186** [colinin/abp-vue-admin-element-typescript#150]
还有通知模块  ，您说会更改实体 ,请问这功能会一起更新嘛

**Comment by GitXieJun** [comment]
大佬快更新吧，看你的代码学到了很多

**Comment by XuJin186** [comment]
> 大佬快更新吧，看你的代码学到了很多

都在等更新啊

**Comment by GitXieJun** [comment]
大佬咋还没更新哦

**Comment by dotnba** [comment]
能不能搭个体验站点啊？

**Comment by GitXieJun** [comment]
我这里搭建了一个hengjiuyy.cn,功能还是蛮齐全，都是好多都看不懂

**Comment by GitXieJun** [comment]
坐等更新

**Comment by XuJin186** [comment]
#151  你们看下这个  有没有兄弟做过的

**Comment by YahuiWong** [comment]
> 我这里搭建了一个hengjiuyy.cn,功能还是蛮齐全，都是好多都看不懂

有相应的docker-compose文件吗？一起学习一下

**Comment by GitXieJun** [comment]
555我直接用IIS搭建的，docker想学但是不会

**Comment by colinin** [comment]
我抽空上来看了下，还是很惶恐的，不好意思啊各位，最近手里的项目接近尾声，就没有时间来更新这个项目了

在这里我回一下，通知和abp4.0的大概在20号左右升级把，升级abp4.0的话，IdentityServer会有大的改动，这个需要按照官方的文档来的，还有就是你们提到的js代理，这个也是不错的注意，可以通过服务名称自动寻找地址，这个我也会加在4.0的后续版本中的，谢谢大家的关注

**Comment by colinin** [comment]
> 能不能搭个体验站点啊？

等我有时间了会的，现在证件过期了，站点申请不了，大概明年吧 :sweat_smile::sweat_smile:

**Comment by colinin** [comment]
> 我这里搭建了一个hengjiuyy.cn,功能还是蛮齐全，都是好多都看不懂

你的站点我看了下，你最好把admin密码改了，公布游客用户，别把微信相关的权限放出来，还有就是需要变更【消息服务】中的websocket地址，不然是没法使用signalr的

**Comment by GitXieJun** [comment]
这个都是我搭建来学习的没有其他用处

**Comment by GitXieJun** [comment]
你说的websocket地址是VUE里面的signalr地址吗

**Comment by colinin** [comment]
> 你说的websocket地址是VUE里面的signalr地址吗

对，通过网关代理的，不能填写内网消息服务地址，应该填写网关暴露的地址与端口，例如网关部署在 api-gateway.cn，那么连接地址应该是 api-gateway.cn/signalr-hubs/xxxx

**Comment by GitXieJun** [comment]
好的，受教了，thanks

**Comment by XuJin186** [comment]
@colinin   是否可以建一个交流群  我们去完善提意见  可以让这个项目更加好

**Comment by GitXieJun** [comment]
好主意

**Comment by colinin** [comment]
动态菜单已发布，前端定义的动态路由现在已无效，预定义菜单数据已经定义在IDataSeedContributor接口，可以参考此接口的实现 PlatformDataSeedContributor来自定义菜单

另外，平台服务启动之前请先执行 dotnet ef databse update 更新数据结构

#159

**Comment by colinin** [comment]
Abp 4.0 的第一个版本已合并，请参阅 #161 中提到的注意事项
