### ISSUE TITLE
【功能性增强】自动生成Axios服务代理

### ISSUE THREAD

**Issue by XuJin186** [colinin/abp-vue-admin-element-typescript#151]
通过Abp的/api/abp/api-definition接口可以拿到Abp控制器和Dto  这样应该就可以生成服务代理了

**Comment by colinin** [comment]
这事不错的建议，我会在4.0的后续版本中进行改善

**Comment by colinin** [comment]
不过这个功能需要强依赖聚合网关

**Comment by XuJin186** [comment]
> 不过这个功能需要强依赖聚合网关

有些必要的依赖不可避免   比如之前提到的分布式权限   我有问过Abp开发人员  他们的回复是可以将网关做成Abp模块  然后这个网关模块依赖所有的*.Application.Contracts

**Comment by colinin** [comment]
![image](https://user-images.githubusercontent.com/35512826/103127949-649ab580-46ce-11eb-9e70-1d129c34b2ff.png)
![image](https://user-images.githubusercontent.com/35512826/103127957-6f554a80-46ce-11eb-9caa-7c8b1cce8645.png)

此方法的三个必要参数必不可少：RemoteServiceName、Controller、Action，而且abp对于Action没有做处理，返回的是Action的原名，所以个人认为这种方法不是很好，你有什么思路没有

**Comment by colinin** [comment]
在这里，理想中的Action应该是传递 GetList，abp-definition中返回的是GetListAsync

**Comment by XuJin186** [comment]
其实是没啥关系的  可以定义参数是否需要Async

**Comment by XuJin186** [comment]
> 在这里，理想中的Action应该是传递 GetList，abp-definition中返回的是GetListAsync
还是这是属于完全的代理   是否需要类似于ABP官方生成angular那种  直接生成代码

**Comment by colinin** [comment]
Abp NG工程中，也是前端定义 url
https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/tenant-management/src/lib/proxy/tenant.service.ts

或许，这只作为一个可选功能来做，在需要的时候再使用它，比如我图中所示，包装为一个HttpProxyMiXin

**Comment by colinin** [comment]
完全使用abp自动api，那是MVC才能做到的事情

**Comment by XuJin186** [comment]
不是自动的Api也可以获取到Action的定义的吧

**Comment by colinin** [comment]
可以找到api的描述文件，不过像我这样做一个mixin，可以简化自己定义dto和api的步骤，但是这样的话，ts以及el-form的功能就弱化了

**Comment by XuJin186** [comment]
HttpProxyMiXin的话  是不是还是需要自己去手动的指定调用哪个控制器的方法？  可否简便一点  就是生成控制器加方法 和Dto的定义   那样子的话是不是更符合

**Comment by colinin** [comment]
就算Abp自己服务内部调用都要去查找RemoteService，然后通过反射来获取控制器和方法，这是不可避免的

**Comment by XuJin186** [comment]
是的  没错  那有RemoteService的特性的控制器  那就是对外开放的   那就可以生成

**Comment by colinin** [comment]
我会把这个改动提交到仓库中，不过个人不建议使用

**Comment by colinin** [comment]
RemoteService只是找到了某个模块，而模块下有多个控制器，每个控制器有多个方法，你需要在调用api时就要知道是哪个控制器的哪个方法

**Comment by XuJin186** [comment]
是的  最起码也是个硬编码吧    而mixi的话需要手动的通过字符串去比对  容易出问题吧

**Comment by colinin** [comment]
而流量都需要经过网关，除非你的网关中定义了相同的地址，否则，可能在HttpProxyMiXin经过网关时会触发404

**Comment by colinin** [comment]
> 是的 最起码也是个硬编码吧 而mixi的话需要手动的通过字符串去比对 容易出问题吧

我参照 Abp 设计了模型绑定，通过MiXin调用会自动拼接所需参数，不会出问题，问题在于网关中的api接口必须与你的模块暴露的地址一致

**Comment by colinin** [comment]
> > 是的 最起码也是个硬编码吧 而mixi的话需要手动的通过字符串去比对 容易出问题吧
> 
> 我参照 Abp 设计了模型绑定，通过MiXin调用会自动拼接所需参数，不会出问题，问题在于网关中的api接口必须与你的模块暴露的地址一致

或者说，我给api网关的数据种子中做一个改动，让他自动发现模块暴露的api地址，并持久化到网关数据库

**Comment by XuJin186** [comment]
> > > 是的 最起码也是个硬编码吧 而mixi的话需要手动的通过字符串去比对 容易出问题吧
> > 
> > 
> > 我参照 Abp 设计了模型绑定，通过MiXin调用会自动拼接所需参数，不会出问题，问题在于网关中的api接口必须与你的模块暴露的地址一致
> 
> 或者说，我给api网关的数据种子中做一个改动，让他自动发现模块暴露的api地址，并持久化到网关数据库

这个也许是一个解决方案

**Comment by XuJin186** [comment]
是否可以生成Dto呢

**Comment by colinin** [comment]
那就把两项功能合并吧，不过我不认为它的优先级很高

**Comment by colinin** [comment]
如果要使用TypeScript，Dto的定义必不可少

**Comment by XuJin186** [comment]
TypeScript  是现在项目中必不可少的了吧

**Comment by colinin** [comment]
> TypeScript 是现在项目中必不可少的了吧

现代化web项目开发中，它是非常重要的，Vue3.0已经针对TypeScript进行了深度优化

**Comment by XuJin186** [comment]
> > TypeScript 是现在项目中必不可少的了吧
> 
> 现代化web项目开发中，它是非常重要的，Vue3.0已经针对TypeScript进行了深度优化

是的  我很早之前就使用了   不过是和react配合
