### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by Mohadin** [colinin/abp-vue-admin-element-typescript#154]
UIs for languages that are read from right-to-left (RTL), such as Arabic and Hebrew, should be mirrored to ensure content is easy to understand.

Mirroring layout

The main difference between left-to-right (LTR) and right-to-left (RTL) language scripts is the direction in which content is displayed:

    LTR languages display content from left to right
    RTL languages display content from right to left

RTL content also affects the direction in which some icons and images are displayed, particularly those depicting a sequence of events.

In general, the passage of time is depicted as left to right for LTR languages, and right to left for RTL languages.
![flexbox-axis](https://user-images.githubusercontent.com/44315266/102316561-34913b00-3f87-11eb-8481-6f61cbc7c5f8.jpg)

**Comment by colinin** [comment]
A detailed description of the problem is required

**Comment by Mohadin** [comment]
> 
> 
> A detailed description of the problem is required

UIs for languages that are read from right-to-left (RTL), such as Arabic and Hebrew, should be mirrored to ensure content is easy to understand.

Mirroring layout

The main difference between left-to-right (LTR) and right-to-left (RTL) language scripts is the direction in which content is displayed:

    LTR languages display content from left to right
    RTL languages display content from right to left

RTL content also affects the direction in which some icons and images are displayed, particularly those depicting a sequence of events.

In general, the passage of time is depicted as left to right for LTR languages, and right to left for RTL languages.
![flexbox-axis](https://user-images.githubusercontent.com/44315266/102316561-34913b00-3f87-11eb-8481-6f61cbc7c5f8.jpg)

**Comment by colinin** [comment]
not think about it now

**Comment by mrs01dev** [comment]
> UIs for languages that are read from right-to-left (RTL), such as Arabic and Hebrew, should be mirrored to ensure content is easy to understand.
> 
> Mirroring layout
> 
> The main difference between left-to-right (LTR) and right-to-left (RTL) language scripts is the direction in which content is displayed:
> 
> ```
> LTR languages display content from left to right
> RTL languages display content from right to left
> ```
> 
> RTL content also affects the direction in which some icons and images are displayed, particularly those depicting a sequence of events.
> 
> In general, the passage of time is depicted as left to right for LTR languages, and right to left for RTL languages.
> ![flexbox-axis](https://user-images.githubusercontent.com/44315266/102316561-34913b00-3f87-11eb-8481-6f61cbc7c5f8.jpg)

I think this issue should go  upstream.
[https://github.com/PanJiaChen/vue-element-admin](url)
