### ISSUE TITLE
前端发布后，首次运行加载超级慢，

### ISSUE THREAD

**Issue by BiggerWu** [colinin/abp-vue-admin-element-typescript#157]
我前端发布在阿里云上，使用的是Nginx。然后我第一次访问时，加载至少要三四十秒，请问是什么问题

**Comment by colinin** [comment]
**/api/abp/application-configuration**，这个接口的问题，第一次运行时缓存中没有数据，所有的数据都需要通过数据库查询，这也是我建议的缓存过期时间调整高一点的原因

**Comment by colinin** [comment]
权限、设置、功能，这些节点越多，这个接口加载越慢，虽然abp官方通过批量查询来解决这个问题，但是也只是很小的优化
