### ISSUE TITLE
Upgrade ABP to 4.0.0

### ISSUE THREAD

**Issue by colinin** [colinin/abp-vue-admin-element-typescript#161]

**Comment by colinin** [comment]
Abp 4.0 changes greatly, especially Identity Server, which requires manual execution of script files. The migration cannot be performed through the dotnet EF command. SQL scripts have been attached under the Identity service path

**Comment by colinin** [comment]
升级到abp 4.0的变动很大，需要手动执行sql脚本以更新数据库，脚本文件在合并提交时上传

**Comment by chnix** [comment]
兄弟，抽空升级一下呗，官方4.0都出来一段时间了

**Comment by colinin** [comment]
这两天都在处理这个事情，Identity Server管理模块改动太大了，前端需要重写好几个组件



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lazyabp"<notifications@github.com&gt;; 
发送时间: 2020年12月24日(星期四) 下午2:36
收件人: "colinin/abp-vue-admin-element-typescript"<abp-vue-admin-element-typescript@noreply.github.com&gt;; 
抄送: "Colin"<colin.in@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [colinin/abp-vue-admin-element-typescript] Upgrade ABP to 4.0.0 (#161)





 
兄弟，抽空升级一下呗，官方4.0都出来一段时间了

**Comment by colinin** [comment]
**关于Abp 4.0 的第一个版本已经合并，在此对于升级的注意事项进行汇总**

> Identity Server 版本变动较大，需要手动进行迁移，对于数据库迁移所需的脚本已经定义在 **AuthServer.Host**  项目根目录下，可以执行此sql文件进行迁移，一些关键表会删除重建，请提前备份数据库

> Identity Server对弈 ApiScope 重新定义，因此各个项目配置文件节点 **AuthServer:ApiName** 也做了变动，请检查配置文件，否则无法解析token

> 由于Docker的一些特殊情况，现在对 Api网关宿主依赖的客户端重命名，具体可以在 **./aspnet-core/configuration/apigateway/LINGYUN.ApiGateway.Host/appsettings.Development.json** 文件查看此节点：**RemoteServices:ApiGateway**、**IdentityClients:ApigatewayHostClient**

> 平台服务（Platform）需要借助身份认证服务（IdentityServer.Admin）查询用户角色，因此在配置文件中定义了Volo.Abp.Http.Client.IdentityModel所以的内部通讯客户端信息，请检查配置文件
