### ISSUE TITLE
文件丢失 File Lost @2020年12月24日 master

### ISSUE THREAD

**Issue by xdqa01** [colinin/abp-vue-admin-element-typescript#162]
\aspnet-core\modules\apigateway\LINGYUN.ApiGateWay.Admin.Domain.Shared\LINGYUN\ApiGateWay\Admin\Localization\DomainShared

**Comment by xdqa01** [comment]
![image](https://user-images.githubusercontent.com/4485973/103081422-dca3a580-4612-11eb-9a47-99234aa53ee8.png)

**Comment by colinin** [comment]
这是一个还处于计划中的网关重构方案，我会在下次提交中删除此项目

**Comment by colinin** [comment]
项目引用已删除
