### ISSUE TITLE
登录续租问题

### ISSUE THREAD

**Issue by BiggerWu** [colinin/abp-vue-admin-element-typescript#178]
我有一个问题，整个架构是否没有设计续租问题，一个活跃用户在使用期间，假设token有效期过了，应该是自动续租，我发现现在貌似是设置一个长期有效的token来解决这个问题

**Comment by colinin** [comment]
在请求API时如果发生401错误会尝试刷新token，刷新token无效重定向到登录页

**Comment by colinin** [comment]
前提是客户端启用离线刷新，scope包含offline_access

**Comment by colinin** [comment]
Long time no reply closed
