### ISSUE TITLE
网关启动失败，网关服务已启动了，是什么情况呢？

### ISSUE THREAD

**Issue by lazyabp** [colinin/abp-vue-admin-element-typescript#181]
Volo.Abp.AbpInitializationException: An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module LINGYUN.ApiGateway.ApiGatewayHostModule, LINGYUN.ApiGateway.Host, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: One or more errors occurred. (Remote service returns error! StatusCode = BadGateway). See the inner exception for details.
 ---> System.AggregateException: One or more errors occurred. (Remote service returns error! StatusCode = BadGateway)
 ---> Volo.Abp.AbpException: Remote service returns error! StatusCode = BadGateway

appsettings配置错了吗？
`{
  "ApiGateway": {
    "AppId": "TEST-APP"//这里是用于Ocelot主机去API服务器获取参数的标识,指定需要获取什么类型的网关配置
  },
  "Redis": {
    "Configuration": "myredis",
    "InstanceName": "LINGYUN.AbpApplication",
    "DefaultDatabase": 10
  },
  "RemoteServices": {
    "ApiGateway": {
      "BaseUrl": "http://api-gateway-service/",
      "IdentityClient": "ApigatewayHostClient"
    }
  }
}`

**Comment by colinin** [comment]
BadGateway 502，网关服务未就绪，看看服务下的日志文件

**Comment by colinin** [comment]
long time no reply, will close this issue soon

**Comment by colinin** [comment]
#189  可能网关服务承载项目与此有关，请拉去最新代码运行
