### ISSUE TITLE
vue可以登录，但postman连接却不可以

### ISSUE THREAD

**Issue by lazyabp** [colinin/abp-vue-admin-element-typescript#182]
![image](https://user-images.githubusercontent.com/71416511/104829115-978a3080-58ab-11eb-8175-ac8b8ed9036d.png)

**Comment by lazyabp** [comment]
`{
    "error": "invalid_grant"
}`

**Comment by lazyabp** [comment]
POST /connect/token HTTP/1.1
Host: localhost:44385
Content-Type: application/x-www-form-urlencoded
Content-Length: 100

password=1q2w3E*&usename=admin&client_id=vue-admin-element&client_secret=1q2w3e*&grant_type=password

**Comment by lazyabp** [comment]
是我弄错了，把username写成了usename

**Comment by OldKing-lion** [comment]
> 是我弄错了，把username写成了usename

你怎么跑起来的，我各种报错
