### ISSUE TITLE
微服务太重了，有时间写个单体框架来学习下？

### ISSUE THREAD

**Issue by OldKing-lion** [colinin/abp-vue-admin-element-typescript#192]
我看了商业版的功能你都有了，如果有单体的能快速写业务的框架就牛逼了，我想写，但是我不会啊，写不出来

**Comment by colinin** [comment]
你说的应该是快速开发框架吧，其实这个项目只是一个入口与管理的，在自己的服务中引用Abp的用户抽象就完全可以作为单体的应用了，其他的都交给领域事件

**Comment by OldKing-lion** [comment]
是的，就是快速开发框架，带认证服务和用户管理的，类似以前的zero和现在的商业版

**Comment by OldKing-lion** [comment]
> 你说的应该是快速开发框架吧，其实这个项目只是一个入口与管理的，在自己的服务中引用Abp的用户抽象就完全可以作为单体的应用了，其他的都交给领域事件

是的，就是快速开发框架，带认证服务和用户管理的，类似以前的zero和现在的商业版

**Comment by colinin** [comment]
我目前正在做一个微商城项目，完成后可以精简代码提交到新仓库，可以参考一下，商城项目是基于abp的，由这个仓库代管部分功能
