### ISSUE TITLE
建议完善文档，等你更新，我会成为第一个生产环境使用的人

### ISSUE THREAD

**Issue by OldKing-lion** [colinin/abp-vue-admin-element-typescript#195]
建议完善文档，等你更新，我会成为第一个生产环境使用的人，我也在看你的代码学习，只是现在还跑不起来，跟着你现在的文档做，不能完全跑起来

**Comment by colinin** [comment]
你们最大的问题应该还是在网关这里是吧

**Comment by OldKing-lion** [comment]
> 你们最大的问题应该还是在网关这里是吧

对的，只能部分跑起

**Comment by colinin** [comment]
好的，我会考虑在全新的服务器上拉去代码找出和我环境不一致的问题的

**Comment by colinin** [comment]
网关问题大部分都是AuthServer配置引起的，整个项目的AuthServer配置必须是一致的，获取的Token解密之后的iss必须与AuthServer中的Host地址一致，如果公布的地址是127.0.0.1，那么Token中iss的地址locahost也是无效的

**Comment by colinin** [comment]
其他自定义的模块和扩展模块会像OSS模块一样提供统一的说明，以前的模块会慢慢添加，以后新增的模块一定会定义README文件
