### ISSUE TITLE
你好，发现系统中几乎用的都是属性注入，请问是基于什么考虑的呢？

### ISSUE THREAD

**Issue by NameIsBad** [colinin/abp-vue-admin-element-typescript#197]

**Comment by OldKing-lion** [comment]
> _No description provided._
abp源码就是这么干的，所以作者也这么写的吧

**Comment by colinin** [comment]
属性注入可以实现按需注入，避免了构造函数中大量的接口注入造成的单元测试问题

**Comment by NameIsBad** [comment]
> 属性注入可以实现按需注入，避免了构造函数中大量的接口注入造成的单元测试问题

嗯 谢啦
