### ISSUE TITLE
LINGYUN.ApiGateway.Host启动后报错

### ISSUE THREAD

**Issue by 121001397** [colinin/abp-vue-admin-element-typescript#198]
1）不运行LINGYUN.ApiGateway.Host项目 ，运行其他所有Host项目，可以正常打开http://localhost:44385/.well-known/openid-configuration。说明IDServer4和AuthServer.host是正常的。
2）运行所有项目时，LINGYUN.ApiGateway.Host项目发生错误，导致所有项目异常退出。
注：其他几个项目只有debug日志，没有错误日日志。但LINGYUN.ApiGateway.Host日志中提示连接http://localhost:44385地址被拒绝；日志如下：
2021-02-04 17:37:54 [FTL] [Microsoft.AspNetCore.Hosting.Diagnostics] [7916] [1] - Application startup exception
Volo.Abp.AbpInitializationException: An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module LINGYUN.ApiGateway.ApiGatewayHostModule, LINGYUN.ApiGateway.Host, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null:
One or more errors occurred. (Could not retrieve the OpenId Connect discovery document! ErrorType: Exception. Error: Error connecting to http://localhost:44385/.well-known/openid-configuration. 由于目标计算机积极拒绝，无法连接。 (localhost:44385).). See the inner exception for details.
 ---> System.AggregateException: One or more errors occurred. (Could not retrieve the OpenId Connect discovery document! ErrorType: Exception. Error: Error connecting to http://localhost:44385/.well-known/openid-configuration. 由于目标计算机积极拒绝，无法连接。 (localhost:44385).)
 ---> Volo.Abp.AbpException: Could not retrieve the OpenId Connect discovery document! ErrorType: Exception. Error: Error connecting to http://localhost:44385/.well-known/openid-configuration. 由于目标计算机积极拒绝，无法连接。 (localhost:44385).

**Comment by OldKing-lion** [comment]
我运行起来，前端访问不了接口直接报错，但是gateway是能启动的

**Comment by colinin** [comment]
网关无法访问身份认证服务器，可能不在同一台主机，如果在容器环境下，请把localhost改为容器链接名称或IP地址

**Comment by 121001397** [comment]
> 网关无法访问身份认证服务器，可能不在同一台主机，如果在容器环境下，请把localhost改为容器链接名称或IP地址

我的是在VS中运行的，RabbitMQ与Redis，数据库都是没问题的。但只要这些host项目同时运行，ApiGateWay.Host项目就报连不上localhost:44385。注：地址时没错的，不运行apiGateWay.Host项目时 http://localhost:44385/.well-known/openid-configuration.地址时可以正常访问的。
目前怀疑可能与认证中心的认证信息有关，导致无法连接上认证中心。

**Comment by 121001397** [comment]
> 我运行起来，前端访问不了接口直接报错，但是gateway是能启动的
我的QQ号：121001397，咱可以加为好友，互相交流使用心得。之前只是简单使用过abp框架，没有用到多租户，领域事件等。启动项目时遇到些问题，解决挺占用时间的。

**Comment by 121001397** [comment]
由于.netCore 与 ABP框架对代码做了较多的封装。目前对网关、认证中心只是了解基本的使用方式，当使用咱的框架运行出现错误时，真的是很不好定位具体原因。原计划利用假期这几天熟悉下咱的框架的，可目前网关与认证中心一直无法建立连接。比较着急。。。。

**Comment by colinin** [comment]
可以发我邮件，colin.in@foxmail.com
