### ISSUE TITLE
建议搭建一个演示站点

### ISSUE THREAD

**Issue by dotnba** [colinin/abp-vue-admin-element-typescript#199]
比看文档直观，一目了然...

**Comment by colinin** [comment]
域名还在申请备案中

**Comment by colinin** [comment]
演示地址：http://47.108.153.4:40000/
用户名：demo
密码：demo123

此账号具有浏览及部分新增权限

**Comment by dotnba** [comment]
> 演示地址：http://47.108.153.4:40000/
> 用户名：demo
> 密码：demo123
> 
> 此账号具有浏览及部分新增权限

谢谢大佬
