### ISSUE TITLE
为了方便引用包，我把它上传到了我的官方nuget账号了，大佬这边什么时候要自己上传了或者其他原因我这边再删掉

### ISSUE THREAD

**Issue by weibinlong** [colinin/abp-vue-admin-element-typescript#209]
![image](https://user-images.githubusercontent.com/16573133/109252502-a825b300-7828-11eb-912b-9e92398d0741.png)

**Comment by colinin** [comment]
整个项目缺少大量的单元测试代码，我就没准备上传到nuget，你要上传也可以，许可协议是MIT就行

**Comment by weibinlong** [comment]
嗯。用的就是MIT，原来的配置参数我都没动的
