### ISSUE TITLE
AuthServer.Host 拿到的TOKEN，访问服务时CurrentUser只有Id有值，其他的都为空

### ISSUE THREAD

**Issue by weibinlong** [colinin/abp-vue-admin-element-typescript#210]
如图一

后面对比了一下token，如下
![image](https://user-images.githubusercontent.com/16573133/109409711-f9bc7200-79cf-11eb-907d-a368c4c19343.png)

![image](https://user-images.githubusercontent.com/16573133/109409734-2d979780-79d0-11eb-9800-58530f357a9f.png)

![image](https://user-images.githubusercontent.com/16573133/109409777-6172bd00-79d0-11eb-9697-d7054558e69a.png)

**Comment by colinin** [comment]
检查下你的API资源、身份资源和API Scope与客户端的Scope
