### ISSUE TITLE
LINGYUN.ApiGateway.Host , "Authorization failed! Given policy has not granted."

### ISSUE THREAD

**Issue by mrs01dev** [colinin/abp-vue-admin-element-typescript#212]
LINGYUN.ApiGateway.Host have Exception  
"error":"invalid_client"

- opening  LINGYUN.ApiGateway.HttpApi.Host  swagger page

http://localhost:30001/swagger/index.html

- section   AggregateReRoute , GET ​/api​/ApiGateway​/Aggregates​/by-AppId​/{AppId}

- testing

http://localhost:30001/api/ApiGateway/Aggregates/by-AppId/TEST-APP

-The  Server response is 

401 | Error: UnauthorizedResponse bodyDownload{   "error": {     "code": "Volo.Authorization:010001",     "message": "Authorization failed! Given policy has not granted.",     "details": null,     "data": {},     "validationErrors": null   } }

 Response headers _abperrorformat: true  content-type: application/json; charset=utf-8  date: Tue02 Mar 2021 05:42:55 GMT  server: Kestrel  transfer-encoding: chunked

Please provide instructions to solve this issue ?

**Comment by colinin** [comment]
First: the apigateway. Host project must be consistent with the apigateway. httpapi.host project's authServer configuration;
Second: to ensure ApiGateway. Host projects the ClientId IdentityClients configuration has the following permissions: ApiGateway.Global, ApiGateway.Global.Export, ApiGateway.Route, ApiGateway.Route.Export, ApiGateway.DynamicRoute, ApiGateway.DynamicRoute.Export, ApiGateway.AggregateRoute, ApiGateway.AggregateRoute.Export

**Comment by colinin** [comment]
Your interface prompts 401 that the configuration of the AuthServer is usually inconsistent and that the client cannot be identified by the Token

**Comment by mrs01dev** [comment]
@colinin  
kindly update configuration file: LINGYUN.ApiGateway.Host/appsettings.Development.json ,
[section IdentityClients ,"ClientId": "ApigatewayHostClient" ] is not accurate!
The  correct is
"ClientId": "apigateway-host-client",
Thanks

**Comment by colinin** [comment]
> @colinin
> kindly update configuration file: LINGYUN.ApiGateway.Host/appsettings.Development.json ,
> [section IdentityClients ,"ClientId": "ApigatewayHostClient" ] is not accurate!
> The correct is
> "ClientId": "apigateway-host-client",
> Thanks

OK，I will update this file

**Comment by weibinlong** [comment]
终于有人找出这个问题了。。
