### ISSUE TITLE
关于EF实体在C#8开启<Nullable>enable</Nullable>时的问题

### ISSUE THREAD

**Issue by NameIsBad** [colinin/abp-vue-admin-element-typescript#214]
在EF实体映射到数据库字段时，值类型可用int? decimal? bool?。 string默认是可为空的。

当开启 __Nullable__ 后，string类型需要改成[_string?_]  [官方链接](https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=fluent-api%2Cwith-nrt#required-and-optional-properties)

不知道下个版本有没有考虑更新呢？

**Comment by colinin** [comment]
我会检查EF Core文档，不过这个设计到的范围很大，还是需要遵循Abp框架的意思

**Comment by colinin** [comment]
因为这个项目是abp的扩展，目前发现abp貌似没有这方面的计划，等待后期观察
