### ISSUE TITLE
Adding user,Non admin Role, try login,Authorization failed! Given policy has not granted

### ISSUE THREAD

**Issue by mrs01dev** [colinin/abp-vue-admin-element-typescript#223]
Only users with admin role can login.
Adding a new user,
When user try to login ,
{"error":{"code":"Volo.Authorization:010001","message":"Authorization failed! Given policy has not granted.","details":null,"data":{},"validationErrors":null}}

Please tell how to allow user to login with out  admin role?

**Comment by colinin** [comment]
Set the default role of Users, which has access to the current user/role menu. If this default role does not exist, new Users will not be able to get the menu list. Fix this problem in the next submission

**Comment by colinin** [comment]
This issue has been fixed. Note: If new users need page access, you need to assign or self-subscribe to user events
