### ISSUE TITLE
AuthServer.Host数据迁移报错

### ISSUE THREAD

**Issue by ai408** [colinin/abp-vue-admin-element-typescript#226]
![image](https://user-images.githubusercontent.com/6188677/112007180-69e98e00-8b5f-11eb-81d8-ef084f7a9fa1.png)

**Comment by colinin** [comment]
针对IdentityServer的迁移，目前最好的方式是删除所有迁移文件（./Migrations目录下的所有文件），再行创建，否则，需要忽略【20201222101851_Upgrade-Abp-4.0.0.cs】并手动运行identity-server-upgrate-4.1.sql文件

详情参考Abp迁移文档：https://docs.abp.io/en/abp/latest/Migration-Guides/Abp-4_0

**Comment by ai408** [comment]
@colinin 谢谢！项目是好项目，但是文档太不完善了，跑起来都困难。
