### ISSUE TITLE
成功运行后台及前端。登录后，后台页面没有菜单列表

### ISSUE THREAD

**Issue by Refactoring** [colinin/abp-vue-admin-element-typescript#23]
前端页面如图：
![TIM截图20200715135614](https://user-images.githubusercontent.com/451129/87509739-c3322100-c6a4-11ea-9704-df0521d8091b.png)

后台没有错误， 前端有错误。
![TIM截图20200715135701](https://user-images.githubusercontent.com/451129/87509744-c75e3e80-c6a4-11ea-9fdd-94162f9b8b0f.png)

```
[HMR] Waiting for update signal from WDS...
start signalr connection...
[2020-07-15T05:51:03.174Z] Information: Normalizing '/signalr-hubs/notifications' to 'http://localhost:9527/signalr-hubs/notifications'.
Failed to load resource: the server responded with a status of 404 (Not Found)
webpack-internal:///./node_modules/@microsoft/signalr/dist/esm/Utils.js:210 [2020-07-15T05:51:03.289Z] Error: Failed to complete negotiation with the server: Error: Not Found
webpack-internal:///./node_modules/@microsoft/signalr/dist/esm/Utils.js:210 [2020-07-15T05:51:03.291Z] Error: Failed to start the connection: Error: Not Found
webpack-internal:///./node_modules/@microsoft/signalr/dist/esm/Errors.js:29 Uncaught (in promise) Error: Not Found
    at new HttpError (webpack-internal:///./node_modules/@microsoft/signalr/dist/esm/Errors.js:29)
    at XMLHttpRequest.xhr.onload (webpack-internal:///./node_modules/@microsoft/signalr/dist/esm/XhrHttpClient.js:75)
```

**Comment by colinin** [comment]
这是因为权限的原因，你必须确保登录的用户或者用户组拥有这个页面的权限：

**Comment by colinin** [comment]
abp框架的种子数据一般都会初始化admin用户及Identity项目的权限

**Comment by colinin** [comment]
至于通知系统的404，需要在网关添加hub的路由

**Comment by Refactoring** [comment]
用CLI创建了个项目，对比发现权限表里，的确是少了数据。用户表中`admin`有创建。   
感觉现有项目是不是少了部分初始化的代码？

**Comment by colinin** [comment]
@Refactoring 查看abp源码： (https://github.com/abpframework/abp/blob/dev/modules/permission-management/src/Volo.Abp.PermissionManagement.Domain/Volo/Abp/PermissionManagement/PermissionDataSeedContributor.cs)

 项目启动会给admin角色授予所有权限，我在启动项目引用了相关模块，权限种子肯定是运行了的，这个项目目前唯一缺失的就是几个网关路由了

**Comment by Refactoring** [comment]
感谢回复，我再研究研究。

**Comment by colinin** [comment]
@Refactoring 
    网关的初始化sql已更新，删除apigateway数据库，重新运行脚本就行了

**Comment by colinin** [comment]
如果还有问题请再开一个issue，这个我就关闭了
