### ISSUE TITLE
【New Module】集成Dapr

### ISSUE THREAD

**Issue by colinin** [colinin/abp-vue-admin-element-typescript#240]
dapr能解决很多微服务的问题，考虑集成Dapr组件

**Comment by colinin** [comment]
在 #239 中，已经完成了对Dapr.Actors的集成

**Comment by XuJin186** [comment]
ABP官方也在集成

**Comment by colinin** [comment]
> ABP官方也在集成

官方还需要等一周之后

**Comment by colinin** [comment]
在 #243 中，完成对Dapr.Client的集成，现在支持 [service-invocation](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/service-invocation-overview/)

**Comment by colinin** [comment]
下一个是dapr的发布订阅，EasyAbp社区已经有一个集成模块了

状态管理理论上来讲集成Dapr.Client获取了全局的DaprClient即可

**Comment by LGinC** [comment]
`LINGYUN.Abp.Dapr.Client` 还没发布到nuget

**Comment by colinin** [comment]
> `LINGYUN.Abp.Dapr.Client` 还没发布到nuget

nuget包不是我本人发布的，个人仅建议克隆项目后在本地nuget服务器发布

**Comment by LGinC** [comment]
好的,谢谢

**Comment by zqhgit001** [comment]
大肠菌素老铁，你的-ABP-VUE项目我我运行不起来啊，是不是版本不对啊？
