### ISSUE TITLE
【新模块】导入导出模块

### ISSUE THREAD

**Issue by XuJin186** [colinin/abp-vue-admin-element-typescript#242]
简单的Excel导入导出的确不值得开发成模块   但是假如是模板导入导出呢 ,导出的话.net圈已经有了  二次封装即可   导入的话   应用场景为   比如一个销售订单   以前客户都是用Excel记录 ,每一个销售员都有自己的模板  但是最终数据模型是一致的  那是否可以让销售员上传一份他自己的模板  在里面一些固定的填写模板参数  比如在A1填写{{Name}}  那这个销售员导入的话的  我们就默认就去A1填充Name字段

**Comment by colinin** [comment]
这个是需要从具体业务层面来做的，我一直没做是因为太繁琐了

思路大概就和Abp的文本模板一致，可以参照多语言管理模块，初始化模板写在本地映射到虚拟文件系统，变动后的模板存在oss里面，模板管理模块从oss去下载

**Comment by XuJin186** [comment]
道理是这么个道理,其实也算是个通用模块,我也是想请教一下我这个思路是否能实现   文本模板我扩展了一下  如商业版一样  的确很简单   但是这个导入的话的确很繁琐
