### ISSUE TITLE
关于通知推送

### ISSUE THREAD

**Issue by ruanbl** [colinin/abp-vue-admin-element-typescript#271]
vue客户端在收到实时通知的时候，data部分得到的值是valuekind=3，而后台推送过去的时候是valuekind=string:“值”。vue客户端需要哪里配置一下吗？
![微信图片_20210531195129](https://user-images.githubusercontent.com/4189120/120189256-add8cd80-c249-11eb-9a77-5590a73a11fe.png)

**Comment by colinin** [comment]
感谢，找时间我把CAP类库的序列化设施用abp的替换掉，让它和框架保持一致

**Comment by ruanbl** [comment]
辛苦了

**Comment by colinin** [comment]
现在全面替换掉了Newtownsoft.Json，cap的序列化设施引用了Volo.Abp.Json的全局配置
