### ISSUE TITLE
vuejs中npm下载包出现错误 大大上传的项目不完整？？？

### ISSUE THREAD

**Issue by Leiloloaa** [colinin/abp-vue-admin-element-typescript#273]
各种方式都试过了：yarn、cnpm和代理 npm 都下不成功，

**Comment by weibinlong** [comment]
我的也是，一直失败

**Comment by colinin** [comment]
node版本降低到14.x，因为前端依赖的某些npm包不支持高版本

**Comment by caiqin00** [comment]
移除tui-editor依赖包和相关组件页面就可以了

**Comment by colinin** [comment]
> 移除tui-editor依赖包和相关组件页面就可以了

没有经过测试，不过分析了此包的依赖树，的确引用了一些不受支持的项目，已在package.json中移除此依赖并删除了markdown组件
