### ISSUE TITLE
Switching the UI framework

### ISSUE THREAD

**Issue by colinin** [colinin/abp-vue-admin-element-typescript#279]
Vue很早就已经发布3.0的正式版了，而且最近发现一个很好用的基于Vue3.0的Admin项目，考虑重写整个UI

项目地址：https://github.com/anncwb/vue-vben-admin
预览地址：https://vvbin.cn/next/

**Comment by colinin** [comment]
这可能需要一个新的仓库地址

**Comment by XuJin186** [comment]
非常不错的项目

**Comment by colinin** [comment]
> 非常不错的项目

第一步的路由适配已经改造完成，使用的Vben Admin精简版，将会发布到新仓库中体验

不过这个项目作者很勤快啊，后期的差异更新比较头大

**Comment by colinin** [comment]
新仓库已经建立：https://github.com/colinin/vue-vben-admin-abp-vnext

几乎不需要修改任何后端代码，只需要重写一些前端页面即可，通过数据字典可以轻松定义适配的路由信息

**Comment by XuJin186** [comment]
我一直觉得blazor的代码复用率很高  一直苦于找不到一个不错的组件库来搭建
