### ISSUE TITLE
创建租户后其创建的用户在前端无法登录

### ISSUE THREAD

**Issue by GitXieJun** [colinin/abp-vue-admin-element-typescript#288]
User authentication failed: 用户名或密码错误!, details: {"ClientId":"vue-admin-element","ClientName":"vue-admin-element","GrantType":"password","Scopes":"address email lingyun-abp-application offline_access openid phone profile role","AuthorizationCode":"********","RefreshToken":"********","UserName":"1@qq.com","AuthenticationContextReferenceClasses":null,"Tenant":null,"IdP":null,"Raw":{"grant_type":"password","username":"1@qq.com","password":"***REDACTED***","client_id":"vue-admin-element","client_secret":"***REDACTED***"},"$type":"TokenRequestValidationLog"}

**Comment by GitXieJun** [comment]
1

**Comment by LuceLuo** [comment]
请问密码错误是怎么解决的呀？
