### ISSUE TITLE
/api/abp/application-configuration -> auth 字段没有权限也都为true

### ISSUE THREAD

**Issue by icxldd** [colinin/abp-vue-admin-element-typescript#290]
![image](https://user-images.githubusercontent.com/16592001/128819908-0a212c62-341d-4c1a-bdbb-a41d6ee151a7.png)
求指导

**Comment by colinin** [comment]
auth.policies为已注册的授权策略，auth.grantedPolicies才是当前主体已授权策略

**Comment by icxldd** [comment]
![image](https://user-images.githubusercontent.com/16592001/128842655-3d8d8cd2-f2ba-4ae5-b269-b5e1f1d0b3fd.png)
大佬 我把这行代码的感叹号去掉，然后客户端权限就正常了。

**Comment by icxldd** [comment]
加了感叹号不是和你的注释相反嘛 ，不知道我理解的对不对- -

**Comment by colinin** [comment]
> ![image](https://user-images.githubusercontent.com/16592001/128842655-3d8d8cd2-f2ba-4ae5-b269-b5e1f1d0b3fd.png)
> 大佬 我把这行代码的感叹号去掉，然后客户端权限就正常了。

这表示初始化abp框架配置，用户没有登录的情况下这个字段是检索下去是undefined，所以要加?操作符

**Comment by colinin** [comment]
这个UI的处理逻辑太混乱了，我也没怎么维护，可以克隆下新UI项目，那边清晰一点（我前端不咋地）

**Comment by icxldd** [comment]
好呗谢谢大佬。我问题解决啦
