### ISSUE TITLE
apigateway数据库的appapigatewayreroute表数据

### ISSUE THREAD

**Issue by icxldd** [colinin/abp-vue-admin-element-typescript#302]
# 非常感谢大佬开源这个开源项目！

我遇到app.apigatewayreroute表数据丢失，好像是只留下了database\ApiGateway-Init.sql 脚本下的数据，
![image](https://user-images.githubusercontent.com/16592001/133728398-46f91a9e-d3d4-4ebf-8a12-ac89cd542ac5.png)
之前有6条数据然后这回启动项目后就之前ApiGateway-Init.sql备份后的3条，

中途因为apigateway-httpapi项目持续报这个错然后apigateway-host起不来
![image](https://user-images.githubusercontent.com/16592001/133728708-c9c3fcf1-ea0b-4e40-96b5-4bc22f85b250.png)
但docker自启动重启1分钟左右 它自己就好了。 但出现上面说的少数据的情况

这个情况大佬知道是什么可能嘛

**Comment by zqhgit001** [comment]
老铁，您LINGYUN.Abp.BackendAdmin.HttpApi.Host这个项目能运行起来吗？

**Comment by icxldd** [comment]
任何一个微服务没跑起来  前端都登陆不上呀    可以运行起来的 ，这个大佬的开源项目非常的友好了

> 老铁，您LINGYUN.Abp.BackendAdmin.HttpApi.Host这个项目能运行起来吗？

**Comment by colinin** [comment]
有个情况说明解释了的，如果存在ApiGateway-Init.sql，启动时是Devlopment环境则会执行它，而这个脚本会**重建表结构**，此过程将清空所有表数据

解决方案是删除初始化脚本或者以Production环境启动

**Comment by colinin** [comment]
> 老铁，您LINGYUN.Abp.BackendAdmin.HttpApi.Host这个项目能运行起来吗？

你那一堆的MySql无法连接、RabbitMQ无法连接造成的服务启动失败，我还是建议你使用这些中间件的时候最好把文档读一遍，了解一下 Orz
