### ISSUE TITLE
LINGYUN.Abp.ApiGateway.Host

### ISSUE THREAD

**Issue by tangningkun** [colinin/abp-vue-admin-element-typescript#377]
LINGYUN.Abp.ApiGateway.Host
这个appsettings.Development.json 大神能贴出来一下吗

**Comment by colinin** [comment]
这是无关紧要的模块

**Comment by tangningkun** [comment]
老铁，我运行vben版本遇到了网关给其他服务授权失败
请问在网关LINGYUN.ApiGateway.Host中是否有其他配置需要处理一下

**Comment by tangningkun** [comment]
即http://localhost:30000/connect/token获取的token调用配置的其他服务
授权失败

**Comment by colinin** [comment]
授权端点不经过网关，直接用44385端点

**Comment by tangningkun** [comment]
![image](https://user-images.githubusercontent.com/37114529/141960883-39ca9bd6-b356-4d90-af0f-7f079867f083.png)
![image](https://user-images.githubusercontent.com/37114529/141961032-0887854d-c689-422e-9df7-d842bdfa8ffc.png)
但是我通过这样传递Token，说我这边没有授权

**Comment by colinin** [comment]
项目中的所有**AuthServer:Authority**配置必须一致，你这里通过网关获取令牌了，其他服务也必须走网关验证令牌

**Comment by colinin** [comment]
这就是为什么设计授权端点不走网关的原因，如果以后网关需要鉴权那就循环依赖了

**Comment by tangningkun** [comment]
我第二张截图是走的网关授权

**Comment by colinin** [comment]
我说的是你各个服务的**AuthServer:Authority**配置项，你没听明白吗

**Comment by colinin** [comment]
> 我说的是你各个服务的**AuthServer:Authority**配置项，你没听明白吗

appsettings.{env}.json文件

**Comment by tangningkun** [comment]
"AuthServer": {
    "Authority": "http://localhost:44385/",
    "ApiName": "lingyun-abp-application"
  },
  我看了一下所有的配置都是配置的这个鉴权
我是否应该将这个修改为http://localhost:30000/

**Comment by colinin** [comment]
对

**Comment by tangningkun** [comment]
非常感谢你的解惑

**Comment by tangningkun** [comment]
最终发现这个鉴权这个 如果在appsettings.{env}.json文件 配置的是 "Authority": "http://localhost:44385/",
那么网关路由配置表appapigatewayreroute 中对应的下游地址也应该是http://localhost:44385
这个情况只是在本地调试
