### ISSUE TITLE
运行后台及前端。登录后，后台页面没有菜单列表 

### ISSUE THREAD

**Issue by GitXieJun** [colinin/abp-vue-admin-element-typescript#38]
![QQ图片20200618083240](https://user-images.githubusercontent.com/45811979/89183259-871a1e00-d5c9-11ea-8d4b-9cbffe840d48.png)
SQL脚本也删除更新过

**Comment by colinin** [comment]
I found a problem with the backend administration service not adding the Ocelot Gateway client permission seed, which is one reason

**Comment by colinin** [comment]
拉取最新的更改，重启backend-admin服务即可初始化admin角色所有权限

**Comment by GitXieJun** [comment]
已经成功运行，非常感谢

**Comment by NiceLisan** [comment]
> 已经成功运行，非常感谢

why i can not run successfully. can you share some key tips about your experience?

**Comment by NiceLisan** [comment]
> 已经成功运行，非常感谢

why i can not run successfully. can you share some key tips about your experience?

**Comment by GitXieJun** [comment]
> > 已经成功运行，非常感谢
> 
> 为什么我不能成功运行。您能否分享一些有关您的体验的关键提示？
晓

**Comment by GitXieJun** [comment]
> > 已经成功运行，非常感谢
> 
> why i can not run successfully. can you share some key tips about your experience?
拉取最新代码，配置好redis和消息队列，然后改下前端的地址就可以了

**Comment by NiceLisan** [comment]
> 取最新代码，配置好redis和消息队列，

can you share your fron-end address configuration？

```

cd vueJs

start-vue-admin.bat ==》run failed


VUE_APP_BASE_API = '你的api网关服务器地址' 

VUE_APP_BASE_IDENTITY_SERVICE = '你的identityService服务器地址'

VUE_APP_BASE_IDENTITY_SERVER = '你的identityServer服务器地址'
```
