### ISSUE TITLE
后端程序调试

### ISSUE THREAD

**Issue by gnsilence** [colinin/abp-vue-admin-element-typescript#45]
对这个开源项目很感兴趣,看着后台框架都是放的模块,后端程序没有sln如何正确进行调试

**Comment by NiceLisan** [comment]
yes, i have the same difficult; but the author take my issue regardless  again and again.
i have to manually write the dotnet build script for all the project. it's so frustrated. 
it's ridiculous that if he don't like to share the key file why he open-source the project to waste  someone like us lots of time to do such meaningless things.

**Comment by GitXieJun** [comment]
反正我是用的笨方法，我成功运行后在吧项目自己添加到sln解决方案中

**Comment by colinin** [comment]
services目录结构都是启动项目，可以通过设置启动项目（也可以是多个）来Debug，具体请阅读Visual Studio 2019操作说明

**Comment by gnsilence** [comment]
> 反正我是用的笨方法，我成功运行后在吧项目自己添加到sln解决方案中

这也算是一种办法,就是得手动添加到解决方案

**Comment by colinin** [comment]
> 反正我是用的笨方法，我成功运行后在吧项目自己添加到sln解决方案中

.bat 脚本都是为了快速启动创建的，你们都不看下脚本内容。。

里面写的其实就是 dotnet run 命令，你随便选一个启动项目，右键设置为启动项目，然后F5就进入调试模式了

**Comment by gnsilence** [comment]
> services目录结构都是启动项目，可以通过设置启动项目（也可以是多个）来Debug，具体请阅读Visual Studio 2019操作说明

这样可以,只是有些依赖项目都得引入进来才能调试,比如AuthServer.Host

**Comment by colinin** [comment]
如果需要自己的项目引用我的模块（这里只介绍模块通过Nuget引用），只需要两个步骤：

1、添加对模块的引用，通过Nuget（本地Nuget服务器）；

2、复制pdb文件到自己的项目路径下，然后打断点F5就行了。

至于你想要实现一键式的调试，那需要符号服务了，据我所知，abp vNext都还没添加到符号调试，我调试abp源码都是通过pdb文件

**Comment by gnsilence** [comment]
> 如果需要自己的项目引用我的模块（这里只介绍模块通过Nuget引用），只需要两个步骤：
> 
> 1、添加对模块的引用，通过Nuget（本地Nuget服务器）；
> 
> 2、复制pdb文件到自己的项目路径下，然后打断点F5就行了。
> 
> 至于你想要实现一键式的调试，那需要符号服务了，据我所知，abp vNext都还没添加到符号调试，我调试abp源码都是通过pdb文件

明白了,谢谢回复,有时间好好研究下,

**Comment by GitXieJun** [comment]
不喜欢用那种dotnet命令，没有解决方案直观哈哈

**Comment by NiceLisan** [comment]
> services目录结构都是启动项目，可以通过设置启动项目（也可以是多个）来Debug，具体请阅读Visual Studio 2019操作说明
 

> 不喜欢用那种dotnet命令，没有解决方案直观哈哈

作者是不是眼瞎，这么多人都指出了缺少SLN的整体解决方案文件，他一直在说可以启动多个项目来DEBUG;**没有SLN解决方案**，怎么可能设置多个启动项目。不想提供SLN解决方案，就直说好了。真是醉了。

Is the author blind? So many people have pointed out that there is a lack of SLN's overall solution file. He has been talking about debugging from starting multiple projects; how can you  set multiple startup projects without the SLN solution file ?  **If you don't want to provide SLN solutions, just say so directly** . I'm so drunk.  

也许他不是用VS2019来开发的吧，用JETBRAIN RIDER 倒是可以缓解一些困难。

**Comment by GitXieJun** [comment]
可以用命令行启动，作者在services写好了的，直接执行就可以了，估计是大神都是通过命令行来操作的

**Comment by NiceLisan** [comment]
用命令行启动的脚本也缺少了appsettings.json配置文件，要自己改一些才能启动。
我做了以下改动才能跑起来：

start-apigateway-admin.bat; 其他脚本做类似变更。
```

@echo off
cls
chcp 65001

echo. 启动网关管理服务

cd .\apigateway\LINGYUN.ApiGateway.HttpApi.Host

if '%1' equ '--publish' goto publish
if '%1' equ '--run' goto run
if '%1' equ '--build' goto build
if '%1' equ '--restore' goto restore
if '%1' equ '' goto run


:publish
dotnet publish -c Release -o ..\..\Publish\apigateway-admin --no-cache --no-restore
copy Dockerfile ..\..\Publish\apigateway-admin \Dockerfile
pause
exit

:run
**copy ..\..\..\configuration\apigateway\LINGYUN.ApiGateway.HttpApi.Host\ .\**
dotnet run 
pause
exit

:restore
dotnet restore
pause
exit

:build
dotnet build
pause
exit
```

**Comment by NiceLisan** [comment]
@GitXieJun 
@GitXieJun
Now, i've managed to run all the backend services success, Can you help me how to start the front-end project, sincere thanks~

**Comment by colinin** [comment]
好吧，你们是对的，我仔细看了下GitHub，sln解决方案的确没加进来，很抱歉

**Comment by NiceLisan** [comment]
> 好吧，你们是对的，我仔细看了下GitHub，sln解决方案的确没加进来，很抱歉
> 
> 现在，拉取最新的代码即可

太感谢啦！！！

**Comment by seamusic** [comment]
非常心痛，手动添加完所有项目，才发现新版本的加上了sln。

**Comment by seamusic** [comment]
复制配置，可使用批处理。

services/copy.bat
`xcopy ..\configuration .\ /E`

**Comment by colinin** [comment]
Close this, create new Issue if there is a problem
