### ISSUE TITLE
缺少 appsettings.Development.json 运行不起来 

### ISSUE THREAD

**Issue by valiantzhao** [colinin/abp-vue-admin-element-typescript#5]

**Comment by colinin** [comment]
@valiantzhao 因为有涉及到内网服务器的参数在里面,我找时间上传一个不敏感的配置文件，其实无非就是CAP、Hangfire、Sql、AuthServer这几个重要参数

**Comment by colinin** [comment]
@valiantzhao 配置文件已经上传，你可以参考里面的注释，改成自己的配置
[https://github.com/colinin/abp-vue-admin-element-typescript/tree/2.9/aspnet-core/configuration](4个启动项目的配置)
