### ISSUE TITLE
 npm run build:prod报错

### ISSUE THREAD

**Issue by GitXieJun** [colinin/abp-vue-admin-element-typescript#53]
![91D44926-0E22-4239-B646-611EC956A4BC](https://user-images.githubusercontent.com/45811979/90018439-80815a00-dcdf-11ea-8df1-6c3376e15204.png)
![69410FBB-0C21-4c96-A278-7A01227417BB](https://user-images.githubusercontent.com/45811979/90018443-81b28700-dcdf-11ea-8bc5-714c68655bbe.png)

**Comment by GitXieJun** [comment]
![91D44926-0E22-4239-B646-611EC956A4BC](https://user-images.githubusercontent.com/45811979/90018488-955ded80-dcdf-11ea-8a16-fde06eb4cfc8.png)
![69410FBB-0C21-4c96-A278-7A01227417BB](https://user-images.githubusercontent.com/45811979/90018504-9a22a180-dcdf-11ea-82b3-2a34d3ee0f0f.png)

**Comment by colinin** [comment]
通过命令行直接运行**npm run build:prod** 呢，我通过命令行和VS Code终端运行没问题

**Comment by GitXieJun** [comment]
通过命令行运行还是不行，但是npm run serve 可以运行，npm run build:prod却不行，难道的是环境的问题？
![QQ图片20200813085621](https://user-images.githubusercontent.com/45811979/90082649-ebb04800-dd42-11ea-9342-67645e8f04a8.png)

**Comment by colinin** [comment]
你的环境和我的开发环境差异就在npm和node版本上，我的node版本是**10.16.0**，npm版本是**6.9.0**，貌似 #50 的问题和你差不多，在前端原作者项目下也有类似的编译错误信息，你可以尝试下基于你的npm和node，把依赖更新一下，或者退级到我这个版本看看

**Comment by GitXieJun** [comment]
前端访问application-configuration需要20几秒，直接访问API却只需要几秒，能帮我解答下吗？
![QQ图片20200816110126](https://user-images.githubusercontent.com/45811979/90325589-34b90400-dfb0-11ea-9822-9af2c8b5bcc5.png)
![QQ图片20200816110129](https://user-images.githubusercontent.com/45811979/90325592-384c8b00-dfb0-11ea-9779-c1484ee6d084.png)

**Comment by colinin** [comment]
Close this, create new Issue if there is a problem
