### ISSUE TITLE
how to trigger the message service in the front-end 

### ISSUE THREAD

**Issue by NiceLisan** [colinin/abp-vue-admin-element-typescript#54]
![image](https://user-images.githubusercontent.com/36815990/90303613-ed644200-dee1-11ea-80d4-628637c0291a.png)

hello,   @colinin  can you help to figure out this issue?  

i need to send an message and get noticed in the above pages. 

sincerely thanks~

**Comment by colinin** [comment]
At present, the active push message API is not published, only the intra-app push message interface is provided. According to the design mode, this is also the case, and the push message should be a matter of concern within the application

**Comment by colinin** [comment]
You can publish notifications in your project through the INotificationDispatcher interface, and you only need a custom NotificationDefinitionProvider

**Comment by colinin** [comment]
Close this, create new Issue if there is a problem
