### ISSUE TITLE
建议开发支持antd版本

### ISSUE THREAD

**Issue by yoli799480165** [colinin/abp-vue-admin-element-typescript#6]
ant-design框架社区影响力比较大，几乎已经成为国内UI标准了。考虑项目推广使用的话建议开发antd版本。
https://github.com/ant-design/ant-design  (react版本)
https://github.com/ant-design/ant-design-pro (react版本)
https://github.com/vueComponent/ant-design-vue (vue版本)
https://github.com/NG-ZORRO/ng-zorro-antd  (angular版本)
https://github.com/ant-design-blazor/ant-design-blazor  (blazor版本)
...

blazor + grpc + abp 强无敌。预计到abp 3.0开始支持grpc了。

**Comment by colinin** [comment]
@yoli799480165 感谢您的关注，因为是业余项目，而且我是主后端的，所以没那么多精力开发其他前端界面，Vue3.0我倒是有考虑

    至于grpc，如果abp支持了我肯定也会支持的，就像【对象存储】一样，我刚创建文件存储模块，abp就已经发布了【BlobStoring】模块，所以我弃用了自己开发的【FileStorage】模块，改为实现了【BlobStoring.Aliyun】模块

**Comment by jonny-xhl** [comment]
> @yoli799480165 感谢您的关注，因为是业余项目，而且我是主后端的，所以没那么多精力开发其他前端界面，Vue3.0我倒是有考虑
> 
> 至于grpc，如果abp支持了我肯定也会支持的，就像【对象存储】一样，我刚创建文件存储模块，abp就已经发布了【BlobStoring】模块，所以我弃用了自己开发的【FileStorage】模块，改为实现了【BlobStoring.Aliyun】模块

Hello!
Could you please leave your contact information?
Because I also work Chongqing.

**Comment by colinin** [comment]
@jonny-xhl 我现在再四川天府新区

**Comment by jonny-xhl** [comment]
> @jonny-xhl 我现在再四川天府新区

Ok,Thank you.
