### ISSUE TITLE
项目引用了绝对路径导致无法生成成功了

### ISSUE THREAD

**Issue by valiantzhao** [colinin/abp-vue-admin-element-typescript#61]
错误	CS0006	未能找到元数据文件“D:\LocalNuget\netstandard2.0\LINGYUN.Abp.IM.dll”

**Comment by colinin** [comment]
暂时先把生成路径替换为默认的 **bin/Debug**，我开发环境这个目录是Nuget包上传路径

**Comment by valiantzhao** [comment]
ok

**Comment by colinin** [comment]
#90 本次提交已经移除了Nuget相关得项目绝对路径引用
