### ISSUE TITLE
可否能请教您关于微信登录这块的问题

### ISSUE THREAD

**Issue by happygb21** [colinin/abp-vue-admin-element-typescript#63]
QQ或者微信或者邮箱都可以

**Comment by colinin** [comment]
colin.in@foxmail.com

**Comment by colinin** [comment]
> #126 在此次提交中完善了微信登录提供程序,现在可以通过如下方式使用微信登录

* 1、通过MVC页面跳转，采用授权码模式

* 2、自行拼接 **IDS**服务的 **connect\token** 参数，采用自定义(**微信**)认证模式
